name: Bandibook Auto File Combine Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Combine files
      run: |
        python3 -m combiner --job CombineJob --source-directory notes --target-directory pages --cache-file combiner/cache.json

    - name: Commit changes
      run: |
        git config --global user.name 'bandibookk'
        git config --global user.email 'bandibookmap@gmail.com'
        git add -u
        git add *
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "bandibook auto file combine"
        fi

    - name: Push changes
      run: |
        git remote set-url origin https://binary-ho@github.com/binary-ho/bandibook.git
        git push origin main
