name: Deploy BandiBook

on:
  workflow_dispatch: # 수동 실행 트리거

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel Deployment without Build Cache
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          curl -X POST "https://api.vercel.com/v13/deployments" \
          -H "Authorization: Bearer $VERCEL_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "name": "bandibook",
            "projectId": "'$VERCEL_PROJECT_ID'",
            "teamId": "'$VERCEL_TEAM_ID'",
            "target": "production",
            "buildCache": false
          }'
